export const constants = {
    DEFAULT_DIFFICULTY_LEVEL: 3,
    DEFAULT_BOARD_WIDTH: 15,
    DEFAULT_BOARD_HEIGHT: 15,
    MIN_OBSTACLES_COUNT: 5,
    MAX_OBSTACLES_COUNT: 20,
    MAX_BOMBS_COUNT: 10
};