sceraios:
  -
    gameProperties:
      boardHeight: 10
      boardWidth: 10
      obstaclesNum: 0
    algorithm1: minimax

    algorithm1Properites:
      minimaxDepth: 3
      analyzeMovesNum: 10
    algorithm2: minimax
    alorithm2Properties:
      minimaxDepth: 3
      analyzeMovesNum: 10
    totalGamesNumber: 10